apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: orders-api
  description: API RESTful para pedidos
spec:
  type: openapi
  lifecycle: production
  owner: equipo-dev
  system: order-system
  definition:
    $text: |
      openapi: 3.0.0
      info:
        title: Orders API
        version: 1.0.0
      paths:
        /orders:
          get:
            summary: Obtener todas las órdenes
