apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-service
  description: Servicio que gestiona las órdenes
spec:
  type: service
  lifecycle: production
  owner: equipo-dev
  system: order-system
